@MovieWebserver_HostAddress = http://localhost:5001


###

Get {{MovieWebserver_HostAddress}}/api/person/

###

Get {{MovieWebserver_HostAddress}}/api/user

###

Get {{MovieWebserver_HostAddress}}/api/user/3

###

GET {{MovieWebserver_HostAddress}}/api/search?keyword=lord%20bobby%20ring&page=1&pageSize=10

###
GET {{MovieWebserver_HostAddress}}/api/search?keyword=lord%20bobby%20ring&page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDU4ODA2MH0.rgohDyZa0k9yAHHF643oYyp3elvcoeefZ8eYSEZns7ZTCwD7FuvxoNS96qVPGBwgXZMz0HaGW5XpRPzksUy0tQ

###




DELETE {{MovieWebserver_HostAddress}}/api/user/9 
Authorize: eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNiIsImV4cCI6MTczMDU3MjQwOH0.NauVY_D9d-etn_t1x4uwDHXNjk6BV7z7Qgue8rjl_7Hi4QewPdP1HrcTrjp3gtdidrVR_442P7uiEH-l3iZ1gw
Accept: application/json


###


 
Get {{MovieWebserver_HostAddress}}/api/user
Accept: application/json

### 

Get {{MovieWebserver_HostAddress}}/api/title/movies
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMyIsImV4cCI6MTczMDQzNzU3MH0.zkR27Hg6pXHZVLBHBFv5S2dW3qqmgvS_nMCvt7Fs-v-hSbpqEMdJq0e_B4K7fmQ3zRa86H6Oauui_rb-Tjc2cw



###
Delete {{MovieWebserver_HostAddress}}/api/user/6/review/7
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMyIsImV4cCI6MTczMDQ0NDA0Mn0.lCH1x0JBbRl1x0cUZpmERwlGthTTIFJQV0ewwTEOULpXTou-VqHqSIrx5eyjMYKf9m0RDJ5kT5jtw0K9HXDxNg
Accept: application/json

###
POST {{MovieWebserver_HostAddress}}/api/title/tt21050232
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNiIsImV4cCI6MTczMDU3MjQwOH0.NauVY_D9d-etn_t1x4uwDHXNjk6BV7z7Qgue8rjl_7Hi4QewPdP1HrcTrjp3gtdidrVR_442P7uiEH-l3iZ1gw

###
PUT {{MovieWebserver_HostAddress}}/api/title/tt10382912/review/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY1MzczNX0.Rp19D3F1msz9yougr6vJ79IjJ1JoJ33QNiMkEKL8YbfSmRRpdjVawXtt_D1VMlzhX_IMo75Gxy6gKgo3qpoI7w
Content-Type: application/json
{
  "Rating": 7,
  "Text": "321h f123o"
}

###

PUT {{MovieWebserver_HostAddress}}/api/user/1/update_email
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY1Njc1NX0.2ppz8ENl78av1ROvRXuGSVmO2r9XlOtEsbewq9Sjv4ZNdnKMfKiHXWyl0W6tFXooQ82aaxr0XkNSM3xYV8eyQA
Accept: application/json
Content-Type: application/json
{
  "Email": "cvdscdscsdcds"
}

### update password

PUT {{MovieWebserver_HostAddress}}/api/user/1/update_password
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDc1MDc4N30.A6F2cQyEdoJ6HKTeFGEeRx0VMi5iCGo6Nf-M4ccdlV2JbU7k3YcPuoGLyy1CvDUhTCvDcvcwms8L4kQWi4DURw
Accept: application/json
Content-Type: application/json
{
  "Password": "MoooooMooooCow"
}

### 

DELETE {{MovieWebserver_HostAddress}}/api/user/1/review/1
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY1Njc1NX0.2ppz8ENl78av1ROvRXuGSVmO2r9XlOtEsbewq9Sjv4ZNdnKMfKiHXWyl0W6tFXooQ82aaxr0XkNSM3xYV8eyQA
Accept: application/json

###

DELETE {{MovieWebserver_HostAddress}}/api/user/1/bookmark/1wptt0181689
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY1Njc1NX0.2ppz8ENl78av1ROvRXuGSVmO2r9XlOtEsbewq9Sjv4ZNdnKMfKiHXWyl0W6tFXooQ82aaxr0XkNSM3xYV8eyQA
Accept: application/json

### get likes

GET {{MovieWebserver_HostAddress}}/api/user/1/likes
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY3Njg0N30.lZXgNJEN7Bj1zgAnjVk3gXYw8ZRYYaljKUIS2ExE9tDTw0KFb22PUMTA8pDWK5IqRskPl6Ol0tAhTmggdUSgcA
Accept: application/json


### create user

POST {{MovieWebserver_HostAddress}}/api/user/CreateUser
Accept: application/json
Content-Type: application/json
{
    "username": "1",
    "password": "1",
    "email": "1"
}


### login

PUT {{MovieWebserver_HostAddress}}/api/user
Accept: application/json
Content-Type: application/json
{
    "username": "1",
    "password": "1"
}

### create review
POST {{MovieWebserver_HostAddress}}/api/title/tt10382912/review
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY3OTIwMX0.VrzmI03nur-yVT6sr33aqvwSWXprk58on1jDrdcoUh1k9eEvgx9etM5ZSuBxGeL7PnHzxaiTlugYDaL72zfhvA
Accept: application/json
Content-Type: application/json
{
  "ReviewText": "Gnojdfoipdsfjpodsvie",
  "Rating": 10
}

### like review
POST {{MovieWebserver_HostAddress}}/api/title/tt10382912/review/1
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY3OTIwMX0.VrzmI03nur-yVT6sr33aqvwSWXprk58on1jDrdcoUh1k9eEvgx9etM5ZSuBxGeL7PnHzxaiTlugYDaL72zfhvA
Accept: application/json
Content-Type: application/json
{
  "Like": 1
}


### delete like again

DELETE {{MovieWebserver_HostAddress}}/api/title/tt10382912/review/1
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY3Njg0N30.lZXgNJEN7Bj1zgAnjVk3gXYw8ZRYYaljKUIS2ExE9tDTw0KFb22PUMTA8pDWK5IqRskPl6Ol0tAhTmggdUSgcA
Accept: application/json


### create bookmark TO DO: FIX

POST {{MovieWebserver_HostAddress}}/api/title/tt10382912/bookmark
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY1Njc1NX0.2ppz8ENl78av1ROvRXuGSVmO2r9XlOtEsbewq9Sjv4ZNdnKMfKiHXWyl0W6tFXooQ82aaxr0XkNSM3xYV8eyQA


### delete user

DELETE {{MovieWebserver_HostAddress}}/api/user/1
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMSIsImV4cCI6MTczMDY1Njc1NX0.2ppz8ENl78av1ROvRXuGSVmO2r9XlOtEsbewq9Sjv4ZNdnKMfKiHXWyl0W6tFXooQ82aaxr0XkNSM3xYV8eyQA
Accept: application/json

