@MovieWebserver_HostAddress = http://localhost:5001



###

Get {{MovieWebserver_HostAddress}}/api/user

###

Get {{MovieWebserver_HostAddress}}/api/user/3

###

Get {{MovieWebserver_HostAddress}}/api/search?keyword=lord%20bobby%20ring&page=1&pageSize=10

###

Post {{MovieWebserver_HostAddress}}/api/user/CreateUser
Accept: application/json
Content-Type: application/json
{
    "username": "3",
    "password": "3",
    "email": "3"
}

###

Put {{MovieWebserver_HostAddress}}/api/user
Accept: application/json
Content-Type: application/json
{
    "username": "3",
    "password": "3"
}

### 
Get {{MovieWebserver_HostAddress}}/api/user
Accept: application/json

### 

Get {{MovieWebserver_HostAddress}}/api/title/movies
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMyIsImV4cCI6MTczMDQzNzU3MH0.zkR27Hg6pXHZVLBHBFv5S2dW3qqmgvS_nMCvt7Fs-v-hSbpqEMdJq0e_B4K7fmQ3zRa86H6Oauui_rb-Tjc2cw


### 

Post {{MovieWebserver_HostAddress}}/api/title/review
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMyIsImV4cCI6MTczMDQzNzU3MH0.zkR27Hg6pXHZVLBHBFv5S2dW3qqmgvS_nMCvt7Fs-v-hSbpqEMdJq0e_B4K7fmQ3zRa86H6Oauui_rb-Tjc2cw
Accept: application/json
Content-Type: application/json
{
  "Username": "3",
  "ReviewText": "bobbyybbyybyb",
  "TitleId": "tt0181689",
  "Rating": 2
}

###

Delete {{MovieWebserver_HostAddress}}/api/user/6/review/7
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMyIsImV4cCI6MTczMDQ0NDA0Mn0.lCH1x0JBbRl1x0cUZpmERwlGthTTIFJQV0ewwTEOULpXTou-VqHqSIrx5eyjMYKf9m0RDJ5kT5jtw0K9HXDxNg
Accept: application/json

